### ISSUE TITLE
Cannot able to build DOS

### ISSUE THREAD

**Issue by aenehc** [DemocracyOS/app#552] opened 2015-01-07 00:10 UTC
Hello guys!

I'm having a trouble trying to run my forked of DemocracyOS and I don't know what to do...
I have the last version of the dev branch and I configured my .netrc file.
So I followed exactly what the guide said (https://github.com/DemocracyOS/app/wiki/Installation).

When I'm running "make" I get that:
![screen shot 2015-01-06 at 11 51 50 pm](https://cloud.githubusercontent.com/assets/2859122/5638306/a454c1b4-9605-11e4-8bda-6ba1971238fc.png)

And when I'm running "make run" I get that:
![screen shot 2015-01-06 at 11 52 48 pm](https://cloud.githubusercontent.com/assets/2859122/5638251/0b76aa5c-9605-11e4-9d90-09d5c70e1add.png)

I tried to clean then redo... but I have the same error each time... 
It's probably me... :/

(I hope this is right place to write this)

**Comment by gvilarino** [comment] 2015-01-07 00:17
Hey @aenehc, thanks for reaching out. The issue here is that you haven't properly set up your github credentials as described under the Note in [the OSX/Unix section of our installation guide](https://github.com/DemocracyOS/app/wiki/Installation#unix-and-osx). Please keep in mind that `password` entry isn't your github password, but an app token; [you can create one here](https://github.com/settings/tokens/new).

A lot of people seem to be reporting this lately, so I'll make it clearer in the guide.

Also: no, this isn't the proper place to report this. You should have used our [official mailing list](https://groups.google.com/forum/#!forum/democracyos-app) as described in our [contribution guidelines](https://github.com/DemocracyOS/app/blob/development/CONTRIBUTING.md). There's actually a whole thread for this issue on the list. But no biggie.

I'll close this since it's not a bug.

**Closed by gvilarino** 2015-01-07 00:17 UTC

**Comment by gvilarino** [comment] 2015-01-07 00:19
By the way, check out how to properly set up the latest version of DemocracyOS [here](https://github.com/DemocracyOS/app/wiki/Migrating-to-0.9.0); you'll need an additional app running if you want to get notifications.

**Comment by aenehc** [comment] 2015-01-07 00:27
Thanks a lot ;)

**Comment by gvilarino** [comment] 2015-01-07 01:25
:+1:
