### ISSUE TITLE
Error at Start

### ISSUE THREAD

**Issue by AlbertFR** [DemocracyOS/app#724] opened 2015-04-03 20:49 UTC
Hi,

I have this error 
democracyos:build Found error resolving dependencies tree TypeError: Cannot call method 'filter' of null +14s
TypeError: Cannot call method 'filter' of null

any ideas ?

I'm on ubuntu 14.04 on an x64 system

**Comment by gvilarino** [comment] 2015-04-07 11:40
@AlbertFR please read the [contribution guidelines](https://github.com/DemocracyOS/app/blob/development/CONTRIBUTING.md) before opening an issue'I'm closing this since it's is a problem with your local repo and not `DemocracyOS` itself.

Questions like these should be asked in [our gitter channel](https://gitter.im/DemocracyOS/app) or [our public google group](groups.google.com/group/democracyos-app).

**Comment by gvilarino** [comment] 2015-04-07 11:40
btw the issue is that you haven't properly configured your github token as stated in the wiki

**Closed by gvilarino** 2015-04-07 11:40 UTC
Labels: declined

**Comment by AlbertFR** [comment] 2015-04-07 17:13
that's working now without any changes...
